type = "javascript"
name = "worker-template"
zone_id = "zone-id"
account_id = "account-id"
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.development]
	workers_dev = true
	account_id = "account-id"
[dev]
	port = 8110
